PROJECT_DIR = "/home/jonnyjack/workspace/FPTAI/research-test/son-hy/physml"

# DATA CONFIGS
DATA_DIR = PROJECT_DIR + "/data"
SAVE_DATA_DIR = DATA_DIR + "/processed"

# LOGGING
LOGFILE = PROJECT_DIR + "/logs/graph.log"

# WANDB CONFIG
WANDB_PROJECT = "physml"
WANDB_DIR = PROJECT_DIR + "/logs"
WANDB_ID = "shwbt55f"

# TRAINING CONFIGS
EPOCHS = 500
BATCH_SIZE = 128
CHECKPOINT_DIR = PROJECT_DIR + "/checkpoints/nn"
LOG_INTERVAL = 20
NUM_WORKERS = 6
PATIENCE = -1

# MODEL CONFIGS
NODE_INPUT_DIM = 6
EDGE_INPUT_DIM = 1
GNN_NODE_OUTPUT_DIM = 16
GNN_EDGE_HIDDEN_DIM = 16
GNN_DROPOUT_RATE = 0.2
NUM_STEP_MESSAGE_PASSING = 4
READOUT_NODE_HIDDEN_DIM = 16
READOUT_NODE_OUTPUT_DIM = 8
READOUT_DROPOUT_RATE = 0.2
POOLING_MODE = "mean"
OUTPUT_DIM = 1

# OPTIMIZER CONFIGS
OPTIMIZER = "adamw"
LEARNING_RATE = 0.0005
WEIGHT_DECAY = 0.01
MOMENTUM = 0.9
